---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: org-user-ghcr-pull-secret
  namespace: kustomize-me
spec:
  refreshInterval: 10m
  secretStoreRef:
    name: bitwarden-secretsmanager
    kind: ClusterSecretStore
  target:
    name: secrets
    template:
      data:
        POSTGRES_DSN: "{{ .POSTGRES_DSN }}"
    creationPolicy: Owner
  data:
    - secretKey: POSTGRES_DSN
      remoteRef:
        key: DATA_UNIVERSE_API_SECRETS_BRANCH_MAIN