apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

# update the namespace
namespace: macrocosmos-sn13-data-universe-api-branch-main

# include base resources
resources:
  - ../../base
  - ingress.yaml
  - external-secret.yaml
  - configmap.yaml

patches:
  - target:
      version: v1
      kind: ConfigMap
      name: config
    patch: |-
      - op: replace
        path: /data/VERSION
        value: sha-NEWTAGREPLACEME

images:
  - name: ghcr.io/macrocosm-os/macrocosm-os/data-universe-api:branch-main
    newTag: sha-NEWTAGREPLACEME