apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

# update the namespace
namespace: macrocosmos-sn13-data-universe-api-branch-main

# include base resources
resources:
  - ../../base
  - ingress.yaml
  - external-secret.yaml

patches:
  - target:
      version: v1
      kind: ConfigMap
      name: config
    patch: |-
      - op: replace
        path: /data/VERSION
        value: sha-c68e61d


commonAnnotations:
  git-version: sha-c68e61d
  concourse.ci/pipeline: data-universe-api
  concourse.ci/job: deploy-service-branch-main

images:
  - name: ghcr.io/macrocosm-os/macrocosm-os/data-universe-api:branch-main
    newTag: sha-c68e61d