"""initial schema

Revision ID: 05e77461b0e6
Revises: 
Create Date: 2025-09-29 17:18:25.860662

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '05e77461b0e6'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('on_demand_jobs',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('expire_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('platform', sa.String(length=256), nullable=False),
    sa.Column('start_date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('end_date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('limit', sa.Integer(), nullable=False),
    sa.Column('keyword_mode', sa.String(length=256), nullable=False),
    sa.Column('payload', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_on_demand_jobs_created_at', 'on_demand_jobs', ['created_at'], unique=False)
    op.create_index(op.f('ix_on_demand_jobs_expire_at'), 'on_demand_jobs', ['expire_at'], unique=False)
    op.create_index(op.f('ix_on_demand_jobs_platform'), 'on_demand_jobs', ['platform'], unique=False)
    op.create_table('on_demand_job_submissions',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('job_id', sa.String(length=64), nullable=False),
    sa.Column('miner_hotkey', sa.String(length=256), nullable=False),
    sa.Column('miner_vtrust', sa.Float(), nullable=False),
    sa.Column('submitted_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('s3_path', sa.String(length=1024), nullable=True),
    sa.ForeignKeyConstraint(['job_id'], ['on_demand_jobs.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('job_id', 'miner_hotkey', name='uq_submission_job_miner')
    )
    op.create_index(op.f('ix_on_demand_job_submissions_job_id'), 'on_demand_job_submissions', ['job_id'], unique=False)
    op.create_index(op.f('ix_on_demand_job_submissions_submitted_at'), 'on_demand_job_submissions', ['submitted_at'], unique=False)
    op.create_index('ix_submissions_job_id_submitted_at', 'on_demand_job_submissions', ['job_id', 'submitted_at'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_submissions_job_id_submitted_at', table_name='on_demand_job_submissions')
    op.drop_index(op.f('ix_on_demand_job_submissions_submitted_at'), table_name='on_demand_job_submissions')
    op.drop_index(op.f('ix_on_demand_job_submissions_job_id'), table_name='on_demand_job_submissions')
    op.drop_table('on_demand_job_submissions')
    op.drop_index(op.f('ix_on_demand_jobs_platform'), table_name='on_demand_jobs')
    op.drop_index(op.f('ix_on_demand_jobs_expire_at'), table_name='on_demand_jobs')
    op.drop_index('ix_on_demand_jobs_created_at', table_name='on_demand_jobs')
    op.drop_table('on_demand_jobs')
    # ### end Alembic commands ###
