---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: application-secrets
  namespace: kustomize-me
spec:
  refreshInterval: 10m
  secretStoreRef:
    name: bitwarden-secretsmanager
    kind: ClusterSecretStore
  target:
    name: secrets
    template:
      data:
        COLDKEYPUB: "{{ .COLDKEYPUB }}"
        CONSTELLATION_API_KEY: " {{ .CONSTELLATION_API_KEY }}"
        DO_SPACES_KEY: "{{ .DO_SPACES_KEY }}"
        DO_SPACES_SECRET: "{{ .DO_SPACES_SECRET }}"
        METRICS_API_KEY: " {{ .METRICS_API_KEY }}"
        POSTGRES_DSN: "{{ .POSTGRES_DSN }}"
        S3_ENDPOINT: "{{ .S3_ENDPOINT }}"
    creationPolicy: Owner
  dataFrom:
    - extract:
        key: DATA_UNIVERSE_API_SECRETS_PRODUCTION