---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: application-secrets
  namespace: kustomize-me
spec:
  refreshInterval: 10m
  secretStoreRef:
    name: bitwarden-secretsmanager
    kind: ClusterSecretStore
  target:
    name: secrets
    template:
      data:
        POSTGRES_DSN: "{{ .POSTGRES_DSN }}"
    creationPolicy: Owner
  dataFrom:
    - extract:
        key: DATA_UNIVERSE_API_SECRETS_PRODUCTION