---
# this is the main application deployment - it runs the data-universe-api service
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app.kubernetes.io/name: data-universe-api
    app.kubernetes.io/instance: data-universe-api
    app.kubernetes.io/component: data-universe-api
    app.kubernetes.io/part-of: data-universe-api
  name: data-universe-api
  namespace: kustomize-me
spec:
  revisionHistoryLimit: 1
  replicas: 3
  selector:
    matchLabels:
      app.kubernetes.io/name: data-universe-api
  template:
    metadata:
      labels:
        app.kubernetes.io/name: data-universe-api
    spec:
      securityContext:
        runAsUser: 1000
        runAsGroup: 1000
        fsGroup: 2000
      serviceAccountName: data-universe-api
      imagePullSecrets:
        - name: ghcr-secret
      volumes:
        - name: coldkeypub
          secret:
            secretName: secrets
            items:
              - key: COLDKEYPUB
                path: coldkeypub.txt
      containers:
      - imagePullPolicy: Always
        volumeMounts:
          - mountPath: .bittensor/wallets/cfusion/coldkeypub.txt
            name: coldkeypub
        securityContext:
          allowPrivilegeEscalation: false
          # readOnlyRootFilesystem: true
          runAsNonRoot: false
        envFrom:
          - configMapRef:
              name: config
          - secretRef:
              name: secrets
        env:
          - name: SERVICE
            value: data-universe-api
          - name: PORT
            value: "8000"
          - name: ENV
            value: stage
          - name: NAMESPACE
            valueFrom:
              fieldRef:
                fieldPath: metadata.namespace
        image: ghcr.io/macrocosm-os/macrocosm-os/data-universe-api:branch-main
        ports:
          - containerPort: 8000
            name: http
        resources:
          limits:
            memory: "512Mi"
          requests:
            memory: "256Mi"
            cpu: "100m"
        readinessProbe:
          httpGet:
            path: /healthcheck
            port: 8000
        livenessProbe:
          httpGet:
            path: /healthcheck
            port: 8000
        name: data-universe-api