---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: org-user-ghcr-pull-secret
  namespace: kustomize-me
spec:
  refreshInterval: 10m
  secretStoreRef:
    name: bitwarden-secretsmanager
    kind: ClusterSecretStore
  target:
    name: ghcr-secret
    template:
      type: kubernetes.io/dockerconfigjson
      data:
        .dockerconfigjson: "{{ .GITHUB_REGISTRY_TOKEN | toString }}"
    creationPolicy: Owner
  data:
    - secretKey: GITHUB_REGISTRY_TOKEN
      remoteRef:
        key: GITHUB_REGISTRY_TOKEN