---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - configmap.yaml
  - deployment.yaml
  - external-secret.yaml
  - namespace.yaml
  - role-binding.yaml
  - roles.yaml
  - service.yaml
  - serviceaccount.yaml
  - service-monitor.yaml