---
apiVersion: v1
kind: Service
metadata:
  labels:
    app.kubernetes.io/name: data-universe-api
    app.kubernetes.io/part-of: data-universe-api
  name: data-universe-api
  namespace: kustomize-me
spec:
  ports:
  - name: service-port
    port: 8000
    protocol: TCP
    targetPort: http
  selector:
    app.kubernetes.io/name: data-universe-api
  type: ClusterIP