apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: data-universe-api
  namespace: kustomize-me
  labels:
    app.kubernetes.io/name: data-universe-api
    app.kubernetes.io/part-of: data-universe-api
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: data-universe-api
  endpoints:
    - targetPort: 8000
      path: /metrics
      interval: 15s
      scrapeTimeout: 10s
